import type { Metadata } from 'next'
import { IBM_Plex_Sans } from 'next/font/google'
import { Providers } from '../Redux/Provider'
import '../styles/global.css'

const fount = IBM_Plex_Sans({ subsets: ['cyrillic', 'latin'], weight: ["400", "500","600", "700"]  })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={fount.className}>
        <Providers>
           {children}
        </Providers>
        </body>
    </html>
  )
}
